/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bsi.prog2;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class TelaInicial extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicial.class.getName());
    String nome;
    int idade;

    public TelaInicial(String nome, int idade) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
        this.nome = nome;
        this.idade = idade;
        labSaudacao.setText("Olá " + nome + ", seja bem vindo!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        labSaudacao = new javax.swing.JLabel();
        btnPingPong = new javax.swing.JButton();
        btnSnake = new javax.swing.JButton();
        btnJogodavelha = new javax.swing.JButton();
        cmbBackground = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panPrincipal.setBackground(java.awt.Color.black);
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labSaudacao.setBackground(new java.awt.Color(255, 255, 255));
        labSaudacao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labSaudacao.setForeground(new java.awt.Color(255, 255, 204));
        labSaudacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panPrincipal.add(labSaudacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 22, 400, 37));

        btnPingPong.setBackground(new java.awt.Color(102, 102, 255));
        btnPingPong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPingPong.setForeground(new java.awt.Color(255, 255, 204));
        btnPingPong.setText("Ping Pong |    °__");
        btnPingPong.addActionListener(this::btnPingPongActionPerformed);
        panPrincipal.add(btnPingPong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 320, 40));

        btnSnake.setBackground(java.awt.Color.darkGray);
        btnSnake.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSnake.setForeground(new java.awt.Color(255, 255, 204));
        btnSnake.setText("Snake |   L .");
        btnSnake.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnSnakeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSnakeFocusLost(evt);
            }
        });
        btnSnake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSnakeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSnakeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSnakeMouseExited(evt);
            }
        });
        btnSnake.addActionListener(this::btnSnakeActionPerformed);
        panPrincipal.add(btnSnake, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 320, 40));

        btnJogodavelha.setBackground(new java.awt.Color(102, 102, 255));
        btnJogodavelha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnJogodavelha.setForeground(new java.awt.Color(255, 255, 204));
        btnJogodavelha.setText("Jogo da Velha |   X / O ");
        btnJogodavelha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJogodavelhaMouseClicked(evt);
            }
        });
        btnJogodavelha.addActionListener(this::btnJogodavelhaActionPerformed);
        panPrincipal.add(btnJogodavelha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 320, 40));

        cmbBackground.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Preto", "Azul", "Ciano", "Amarelo", " " }));
        cmbBackground.addItemListener(this::cmbBackgroundItemStateChanged);
        cmbBackground.addActionListener(this::cmbBackgroundActionPerformed);
        panPrincipal.add(cmbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 70, 20));

        jLabel2.setText("Cor de fundo");
        panPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 256, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPingPongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPingPongActionPerformed
        new PingPong().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPingPongActionPerformed

    private void btnSnakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSnakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSnakeActionPerformed

    private void btnJogodavelhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogodavelhaActionPerformed
        new JogoDaVelha().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJogodavelhaActionPerformed

    private void btnJogodavelhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJogodavelhaMouseClicked
        new JogoDaVelha().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJogodavelhaMouseClicked

    private void btnSnakeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSnakeFocusGained
        btnSnake.setBackground(Color.red);
    }//GEN-LAST:event_btnSnakeFocusGained

    private void btnSnakeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSnakeFocusLost
        btnSnake.setBackground(Color.DARK_GRAY);

    }//GEN-LAST:event_btnSnakeFocusLost

    private void btnSnakeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSnakeMouseEntered
        btnSnake.setBackground(Color.red);
    }//GEN-LAST:event_btnSnakeMouseEntered

    private void btnSnakeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSnakeMouseExited
        btnSnake.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_btnSnakeMouseExited

    private void btnSnakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSnakeMouseClicked
        JOptionPane.showMessageDialog(this, "Jogo em desenvolvimento, aguarde as proximas atualizações");

    }//GEN-LAST:event_btnSnakeMouseClicked

    private void cmbBackgroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBackgroundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBackgroundActionPerformed

    private void cmbBackgroundItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBackgroundItemStateChanged
    String corSelecionada = cmbBackground.getSelectedItem().toString();
    
    java.awt.Color cor;
    

    cor = switch (corSelecionada) {
            case "Azul" -> java.awt.Color.BLUE;
            case "Ciano" -> java.awt.Color.CYAN;
            case "Preto" -> java.awt.Color.BLACK;
            case "Amarelo" -> java.awt.Color.yellow;
            default -> java.awt.Color.BLACK;
        };
    
    panPrincipal.setBackground(cor);
    }//GEN-LAST:event_cmbBackgroundItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogodavelha;
    private javax.swing.JButton btnPingPong;
    private javax.swing.JButton btnSnake;
    private javax.swing.JComboBox<String> cmbBackground;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labSaudacao;
    private javax.swing.JPanel panPrincipal;
    // End of variables declaration//GEN-END:variables
}
