/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bsi.prog2;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class TelaLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    String nome;
    int idade;

    public TelaLogin() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        labSaudacao1 = new javax.swing.JLabel();
        labSaudacao2 = new javax.swing.JLabel();
        labNome = new javax.swing.JLabel();
        labidade = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        spnIdade = new javax.swing.JSpinner();
        btnEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtAvisoIdade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panPrincipal.setBackground(new java.awt.Color(0, 0, 51));
        panPrincipal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panPrincipalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                panPrincipalFocusLost(evt);
            }
        });

        labSaudacao1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labSaudacao1.setForeground(new java.awt.Color(255, 255, 204));
        labSaudacao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSaudacao1.setText("Olá, seja bem vindo!");

        labSaudacao2.setBackground(new java.awt.Color(255, 255, 255));
        labSaudacao2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labSaudacao2.setForeground(new java.awt.Color(255, 255, 255));
        labSaudacao2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSaudacao2.setText("Para iniciar, digite seu nome e insira sua idade.");

        labNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labNome.setForeground(new java.awt.Color(255, 255, 204));
        labNome.setText("Nome:");

        labidade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labidade.setForeground(new java.awt.Color(255, 255, 204));
        labidade.setText("Idade:");

        txtNome.setBackground(new java.awt.Color(153, 204, 255));
        txtNome.addActionListener(this::txtNomeActionPerformed);
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        spnIdade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spnIdade.addChangeListener(this::spnIdadeStateChanged);
        spnIdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spnIdadeKeyPressed(evt);
            }
        });

        btnEntrar.setBackground(java.awt.Color.cyan);
        btnEntrar.setText("Entrar");
        btnEntrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnEntrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnEntrarFocusLost(evt);
            }
        });
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntrarMouseExited(evt);
            }
        });
        btnEntrar.addActionListener(this::btnEntrarActionPerformed);

        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setText("para maiores de 13 anos");

        btnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelar.setText("Cancelar");
        btnCancelar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCancelarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCancelarFocusLost(evt);
            }
        });
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
        });
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        txtAvisoIdade.setBackground(new java.awt.Color(0, 0, 51));
        txtAvisoIdade.setBorder(null);
        txtAvisoIdade.addActionListener(this::txtAvisoIdadeActionPerformed);

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labSaudacao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labSaudacao2, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEntrar)
                .addGap(17, 17, 17))
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addComponent(labNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addComponent(labidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAvisoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(labSaudacao1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labSaudacao2))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labidade)
                            .addComponent(spnIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAvisoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar)
                    .addComponent(btnCancelar))
                .addGap(15, 15, 15))
        );

        getContentPane().add(panPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        nome = txtNome.getText();
        idade = (int) spnIdade.getValue();
        if (idade < 13) {
            JOptionPane.showMessageDialog(this, "Idade inválida");
        } else {
            new TelaInicial(nome, idade).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseEntered

        btnEntrar.setBackground(Color.green);

    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
        btnEntrar.setBackground(Color.blue);
    }//GEN-LAST:event_btnEntrarMouseEntered

    private void btnEntrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnEntrarFocusGained
        btnEntrar.setBackground(Color.green);

    }//GEN-LAST:event_btnEntrarFocusGained

    private void btnEntrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnEntrarFocusLost
        btnEntrar.setBackground(Color.blue);
    }//GEN-LAST:event_btnEntrarFocusLost

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnEntrar.doClick();
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void spnIdadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnIdadeKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnEntrar.doClick();
        }
    }//GEN-LAST:event_spnIdadeKeyPressed

    private void panPrincipalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panPrincipalFocusGained
    }//GEN-LAST:event_panPrincipalFocusGained

    private void panPrincipalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panPrincipalFocusLost
    }//GEN-LAST:event_panPrincipalFocusLost

    private void btnCancelarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCancelarFocusGained
        int largura = panPrincipal.getWidth();
        int altura = panPrincipal.getHeight();

        int x = (int) (Math.random() * (largura - btnCancelar.getWidth()));
        int y = (int) (Math.random() * (altura - btnCancelar.getHeight()));

        btnCancelar.setLocation(x, y);

    }//GEN-LAST:event_btnCancelarFocusGained

    private void btnCancelarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCancelarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarFocusLost

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        int largura = panPrincipal.getWidth();
        int altura = panPrincipal.getHeight();

        int x = (int) (Math.random() * (largura - btnCancelar.getWidth()));
        int y = (int) (Math.random() * (altura - btnCancelar.getHeight()));

        btnCancelar.setLocation(x, y);
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void spnIdadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnIdadeStateChanged
        int idade = (int) spnIdade.getValue();

        if (idade < 13) {
            txtAvisoIdade.setForeground(Color.RED);
            txtAvisoIdade.setText("Idade inválida");
        } else {
            txtAvisoIdade.setForeground(Color.GREEN);
            txtAvisoIdade.setText("Idade válida");
        }
    }//GEN-LAST:event_spnIdadeStateChanged

    private void txtAvisoIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvisoIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvisoIdadeActionPerformed

    private void btnEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseExited
        btnEntrar.setBackground(Color.cyan);
    }//GEN-LAST:event_btnEntrarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labNome;
    private javax.swing.JLabel labSaudacao1;
    private javax.swing.JLabel labSaudacao2;
    private javax.swing.JLabel labidade;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JSpinner spnIdade;
    private javax.swing.JTextField txtAvisoIdade;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
